# Generated by Django 4.2.2 on 2023-08-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestName', models.CharField(max_length=50)),
                ('TestDateTime', models.DateTimeField()),
                ('Cell', models.CharField(max_length=50)),
                ('VehicleID', models.CharField(max_length=50)),
                ('DriveTrace', models.CharField(max_length=50)),
                ('Engineer', models.CharField(max_length=50)),
                ('Driver', models.CharField(max_length=50)),
                ('IWR', models.FloatField()),
                ('RMSSE', models.FloatField()),
                ('TotalCOgkm', models.FloatField()),
                ('TotalCO2gkm', models.FloatField()),
            ],
        ),
    ]
